### ISSUE TITLE
关于 domain 模块不再使用的疑惑

### ISSUE THREAD

**Issue by alsotang** [node-modules/graceful#10]
![image](https://cloud.githubusercontent.com/assets/1147375/20181838/b3443f08-a79a-11e6-885a-0ae825f61469.png)

这个 readme 里面写着 domain 的介绍，可是源码里面已经没有 domain 的代码了。是否 readme 比较旧？
另外，graceful 此模块目前还推荐使用吗？

**Comment by alsotang** [comment]
![image](https://cloud.githubusercontent.com/assets/1147375/20181937/ffba8c2a-a79a-11e6-833b-ace7ada4c2b3.png)

这个链接失效了

**Comment by fengmk2** [comment]
推荐使用，我们一直用着

**Comment by freeozyl80** [comment]
express_with_cluster 里面的app.js的 有关err.domain_thrown的中间件是不是也废弃了，没看到应该怎么跳进去。

**Comment by fengmk2** [comment]
![image](https://user-images.githubusercontent.com/156269/47762571-32f95000-dcf8-11e8-8cd2-01db690bab2a.png)

https://nodejs.org/dist/latest-v10.x/docs/api/domain.html
