### ISSUE TITLE
关于 graceful 与 domain-middleware 功能上的差异的疑问

### ISSUE THREAD

**Issue by johvin** [node-modules/graceful#11]
@fengmk2 最近我在学习 Express 的错误处理方面的内容，了解到 graceful 与 domain-middleware。比较了下两者的源代码，大体上的逻辑是一样的，唯一的区别是 domain-middleware 对当前出错的请求可以返回一个信息，但是我在 graceful 中没有找到，这个应该是基于 process.on('uncaughtException') 的解决方案的一个缺陷吧（希望我没有遗漏）。如果说想把这个缺陷填补上，还有别的办法吗？不知道阿里这边是怎么解决的？

**Comment by fengmk2** [comment]
domain 做不到的，graceful readme里面有说明。我们是结合cfork + graceful来实现的。最新的实现是egg-cluster，详细可以看看这篇文档 https://eggjs.org/zh-cn/advanced/cluster.html

**Comment by johvin** [comment]
我看了一下 cfork 以及 graceful 的源码，里面没有对当前出错的 request 返回一个友好的信息，graceful 里面有一段处理：

```js
server.on('request', function (req, res) {
  // ...
});
```
看 node api 文档，request 事件是每当有新请求过来的时候才会触发的。所以对于当前出错的 request 请求，是没有进行特别处理的吧？

**Comment by fengmk2** [comment]
> 当前出错的 request 请求，是没有进行特别处理的吧？

当前出错的请求，是无法处理的了。
